name: stolk
description: Stolk - News aggregator

publish_to: "none"
version: 0.5.0+23

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  bloc: ^8.0.1
  flutter_bloc: ^8.0.0
  bloc_concurrency: ^0.2.0
  equatable: ^2.0.0
  easy_localization: ^3.0.0
  dio: ^4.0.0
  flutter_secure_storage: ^5.0.2
  hive: ^2.0.2
  hive_flutter: ^1.0.0
  cached_network_image: ^3.0.0
  flutter_inappwebview: ^5.3.2
  shimmer: ^2.0.0
  timeago: ^3.0.2
  package_info_plus: ^1.0.3
  share_plus: ^3.0.4
  firebase_messaging: ^11.1.0
  firebase_analytics: ^9.0.2
  firebase_core: ^1.3.0
  firebase_crashlytics: ^2.1.1
  modal_bottom_sheet: ^2.0.0
  like_button: ^2.0.2
  url_launcher: ^6.0.10
  animations: ^2.0.1
  google_sign_in: ^5.1.0
  flutter_facebook_auth: ^4.0.1
  animated_text_kit: ^4.2.1
  lottie: ^1.2.1
  auto_size_text: ^3.0.0
  google_mobile_ads: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.0.1
  build_runner: ^2.0.0
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/flags/
    - assets/icons/
    - assets/static/
    - assets/lottie/
