export const langs = [
  { id: 0, name: "az" },
  { id: 1, name: "tr" },
  { id: 2, name: "ru" },
  { id: 3, name: "en" },
];

export const sources = [
  {
    id: 1,
    name: "Oxu.az AZ",
    link: "https://oxu.az/feed",
    logo_suffix: "oxu-az.jpg",
    lang_id: 0,
  },
  {
    id: 2,
    name: "Report.az",
    link: "https://report.az/rss",
    logo_suffix: "report-az.jpg",
    lang_id: 0,
  },
  {
    id: 3,
    name: "Apa.az RU",
    link: "https://apa.az/ru/rss",
    logo_suffix: "apa-az.jpg",
    lang_id: 2,
  },
  {
    id: 4,
    name: "Apa.az AZ",
    link: "https://apa.az/az/rss",
    logo_suffix: "apa-az.jpg",
    lang_id: 0,
  },
  {
    id: 5,
    name: "Metbuat.az",
    link: "https://metbuat.az/rss.xml",
    logo_suffix: "metbuat-az.jpg",
    lang_id: 0,
  },
  {
    id: 6,
    name: "Azertag.az",
    link: "https://azertag.az/rss",
    logo_suffix: "azertag-az.jpg",
    lang_id: 0,
  },
  {
    id: 7,
    name: "Lent.az",
    link: "https://lent.az/rss",
    logo_suffix: "lent-az.jpg",
    lang_id: 0,
  },
  {
    id: 8,
    name: "Trend.az",
    link: "https://az.trend.az/feeds/index.rss",
    logo_suffix: "trend-az.jpg",
    lang_id: 0,
  },
  {
    id: 9,
    name: "Day.az",
    link: "https://news.day.az/rss/",
    logo_suffix: "day-az.jpg",
    lang_id: 0,
  },
  {
    id: 10,
    name: "Yenisabah.az",
    link: "https://yenisabah.az/rss/latest-posts",
    logo_suffix: "yenisabah-az.jpg",
    lang_id: 0,
  },
  {
    id: 11,
    name: "Qafqazinfo.az",
    link: "https://qafqazinfo.az/rss",
    logo_suffix: "qafqazinfo-az.jpg",
    lang_id: 0,
  },
  {
    id: 12,
    name: "Milli.az",
    link: "https://www.milli.az/feed.php",
    logo_suffix: "milli-az.jpg",
    lang_id: 0,
  },
  {
    id: 13,
    name: "Musavat.com",
    link: "https://musavat.com/rss.xml",
    logo_suffix: "musavat-com.jpg",
    lang_id: 0,
  },
  {
    id: 14,
    name: "Olke.az",
    link: "https://olke.az/feed",
    logo_suffix: "olke-az.jpg",
    lang_id: 0,
  },
  {
    id: 15,
    name: "Sputnik.az",
    link: "https://sputnik.az/export/rss2/archive/index.xml",
    logo_suffix: "sputnik-az.jpg",
    lang_id: 0,
  },
  {
    id: 16,
    name: "Haqqin.az",
    link: "https://haqqin.az/rss.xml",
    logo_suffix: "haqqin-az.jpg",
    lang_id: 0,
  },
  {
    id: 17,
    name: "Meduza.io",
    link: "https://meduza.io/rss2/all",
    logo_suffix: "meduza-io.jpg",
    lang_id: 2,
  },
  {
    id: 18,
    name: "Iz.ru",
    link: "https://iz.ru/xml/rss/all.xml",
    logo_suffix: "iz-ru.jpg",
    lang_id: 2,
  },
  {
    id: 19,
    name: "Rbc.ru",
    link: "http://static.feed.rbc.ru/rbc/logical/footer/news.rss",
    logo_suffix: "rbc-ru.jpg",
    lang_id: 2,
  },
  {
    id: 20,
    name: "Rt.com",
    link: "https://russian.rt.com/rss",
    logo_suffix: "rt-com.jpg",
    lang_id: 2,
  },
  {
    id: 21,
    name: "Ria.ru",
    link: "https://ria.ru/export/rss2/archive/index.xml",
    logo_suffix: "ria-ru.jpg",
    lang_id: 2,
  },
  {
    id: 22,
    name: "Lenta.ru",
    link: "https://lenta.ru/rss",
    logo_suffix: "lenta-ru.jpg",
    lang_id: 2,
  },
  {
    id: 23,
    name: "Vesti.ru",
    link: "https://www.vesti.ru/vesti.rss",
    logo_suffix: "vesti-ru.jpg",
    lang_id: 2,
  },
  {
    id: 24,
    name: "Oxu.az RU",
    link: "https://ru.oxu.az/feed",
    logo_suffix: "oxu-az.jpg",
    lang_id: 2,
  },
  {
    id: 25,
    name: "Hurriyet.com.tr",
    link: "http://www.hurriyet.com.tr/rss/anasayfa",
    logo_suffix: "hurriyet-com-tr.jpg",
    lang_id: 1,
  },
  {
    id: 26,
    name: "Webrazzi.com",
    link: "https://webrazzi.com/feed",
    category_alias_name: "technology",
    logo_suffix: "webrazzi-com.jpg",
    lang_id: 1,
  },
  {
    id: 27,
    name: "Transfermarkt.com.tr",
    link: "https://www.transfermarkt.com.tr/rss/news",
    category_alias_name: "sport",
    logo_suffix: "transfermarkt-com-tr.jpg",
    lang_id: 1,
  },
  {
    id: 28,
    name: "Haberler.com",
    logo_suffix: "haberler-com.jpg",
    link: "https://rss.haberler.com/rss.asp",
    lang_id: 1,
  },
  {
    id: 29,
    name: "Sabah.com.tr",
    logo_suffix: "sabah-com-tr.jpg",
    link: "https://www.sabah.com.tr/rss/anasayfa.xml",
    lang_id: 1,
  },
  {
    id: 30,
    name: "Haberturk.com",
    logo_suffix: "haberturk-com.jpg",
    link: "https://www.haberturk.com/rss",
    lang_id: 1,
  },
  {
    id: 31,
    name: "Fontanka.ru",
    logo_suffix: "fontanka-ru.jpg",
    link: "https://www.fontanka.ru/rss.xml",
    lang_id: 2,
  },
  {
    id: 32,
    name: "Sports.ru",
    logo_suffix: "sports-ru.jpg",
    link: "https://www.sports.ru/rss/main.xml",
    category_alias_name: "sport",
    lang_id: 2,
  },
  {
    id: 33,
    name: "Gazeta.ru",
    link: "https://www.gazeta.ru/export/rss/lenta.xml",
    logo_suffix: "gazeta-ru.jpg",
    lang_id: 2,
  },
  {
    id: 34,
    name: "Cnnturk.com",
    link: "https://www.cnnturk.com/feed/rss/all/news",
    logo_suffix: "cnnturk-com.jpg",
    lang_id: 1,
  },
  {
    id: 35,
    name: "BBC Azeri",
    logo_suffix: "bbc-com.jpg",
    link: "https://feeds.bbci.co.uk/azeri/rss.xml",
    lang_id: 0,
  },
  {
    id: 36,
    name: "BBC Türkçe",
    logo_suffix: "bbc-com.jpg",
    link: "https://feeds.bbci.co.uk/turkce/rss.xml",
    lang_id: 1,
  },
  {
    id: 37,
    name: "BBC Russian",
    logo_suffix: "bbc-com.jpg",
    link: "https://feeds.bbci.co.uk/russian/rss.xml",
    lang_id: 2,
  },
  {
    id: 38,
    name: "Baku.ws AZ",
    logo_suffix: "baku-ws.jpg",
    link: "https://baku.ws/rss.xml",
    lang_id: 0,
  },
  {
    id: 39,
    name: "Baku.ws RU",
    logo_suffix: "baku-ws.jpg",
    link: "https://ru.baku.ws/rss.xml",
    lang_id: 2,
  },
  {
    id: 40,
    name: "Teleqraf.com",
    logo_suffix: "teleqraf-com.jpg",
    link: "https://teleqraf.com/feed.php",
    lang_id: 0,
  },
  {
    id: 41,
    name: "Afn.az",
    logo_suffix: "afn-az.jpg",
    link: "https://afn.az/rss.xml",
    lang_id: 0,
  },
  {
    id: 42,
    name: "Publika.az",
    logo_suffix: "publika-az.jpg",
    link: "https://publika.az/rss/",
    lang_id: 0,
  },
  {
    id: 43,
    name: "Yenicag.az",
    logo_suffix: "yenicag-az.jpg",
    link: "https://yenicag.az/feed",
    lang_id: 0,
  },
  {
    id: 44,
    name: "Yenicag.info",
    logo_suffix: "yenicag-info.jpg",
    link: "https://yenicag.info/feed",
    lang_id: 1,
  },
  {
    id: 45,
    name: "Novayaepoxa.com",
    logo_suffix: "novayaepoxa-com.jpg",
    link: "https://novayaepoxa.com/feed",
    lang_id: 2,
  },
  {
    id: 46,
    name: "Vesti.az",
    logo_suffix: "vesti-az.jpg",
    link: "https://vesti.az/rss",
    lang_id: 0,
  },
  {
    id: 47,
    name: "The Guardian UK",
    logo_suffix: "theguardian-com.jpg",
    link: "https://theguardian.com/uk/rss",
    category_alias_name: "united kingdom",
    lang_id: 3,
  },
  {
    id: 48,
    name: "The Guardian World",
    logo_suffix: "theguardian-com.jpg",
    link: "https://theguardian.com/world/rss",
    lang_id: 3,
  },
  {
    id: 49,
    name: "The Guardian Football",
    logo_suffix: "theguardian-com.jpg",
    link: "https://theguardian.com/football/rss",
    category_alias_name: "football",
    lang_id: 3,
  },
  {
    id: 50,
    name: "New York Times",
    logo_suffix: "nytimes-com.jpg",
    link: "https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml",
    lang_id: 3,
  },
  {
    id: 51,
    name: "CNN International Edition",
    logo_suffix: "cnn-com.jpg",
    link: "http://rss.cnn.com/rss/edition.rss",
    lang_id: 3,
  },
  {
    id: 52,
    name: "CNN Football Edition",
    logo_suffix: "cnn-com.jpg",
    link: "http://rss.cnn.com/rss/edition_football.rss",
    category_alias_name: "football",
    lang_id: 3,
  },
  {
    id: 53,
    name: "Caught Offside",
    logo_suffix: "caughtoffside-com.jpg",
    link: "https://www.caughtoffside.com/feed",
    category_alias_name: "football",
    lang_id: 3,
  },
  {
    id: 54,
    name: "TEAMTalk",
    logo_suffix: "teamtalk-com.jpg",
    link: "https://www.teamtalk.com/rss",
    category_alias_name: "football",
    lang_id: 3,
  },
  {
    id: 55,
    name: "Goal",
    logo_suffix: "goal-com.jpg",
    link: "https://goal.com/feeds/en/news",
    category_alias_name: "football",
    lang_id: 3,
  },
  {
    id: 56,
    name: "Goal Türkçe",
    logo_suffix: "goal-com.jpg",
    link: "https://goal.com/feeds/tr/news",
    category_alias_name: "football",
    lang_id: 1,
  },
  {
    id: 57,
    name: "BBC World",
    logo_suffix: "bbc-com.jpg",
    link: "https://feeds.bbci.co.uk/news/world/rss.xml",
    category_alias_name: "world",
    lang_id: 3,
  },
  {
    id: 58,
    name: "BBC Edition",
    logo_suffix: "bbc-com.jpg",
    link: "https://feeds.bbci.co.uk/news/rss.xml",
    lang_id: 3,
  },
  {
    id: 59,
    name: "Kulis.az",
    logo_suffix: "kulis-az.jpg",
    link: "https://kulis.az/rss",
    lang_id: 0,
  },
];

export const categories = [
  {
    name: "culture",
    image_suffix: "culture.jpg",
  },
  { name: "economics", image_suffix: "economics.jpg" },
  { name: "incident", image_suffix: "incident.jpg" },
  { name: "interesting", image_suffix: "interesting.jpg" },
  { name: "life", image_suffix: "life.jpg" },
  { name: "politics", image_suffix: "politics.jpg" },
  { name: "society", image_suffix: "society.jpg" },
  { name: "sport", image_suffix: "sport.jpg" },
  { name: "technology", image_suffix: "technology.jpg" },
  { name: "world", image_suffix: "world.jpg" },
];
