export const langs = [
  { id: 0, name: "az" },
  { id: 1, name: "tr" },
  { id: 2, name: "ru" },
  { id: 3, name: "en" },
];

export const sources = [
  {
    id: 1,
    name: "oxu.az/az",
    link: "https://oxu.az/feed",
    logo_suffix: "oxu-az.jpg",
    lang_id: 0,
  },
  {
    id: 2,
    name: "report.az",
    link: "https://report.az/rss",
    logo_suffix: "report-az.jpg",
    lang_id: 0,
  },
  {
    id: 3,
    name: "apa.az/ru",
    link: "https://apa.az/ru/rss",
    logo_suffix: "apa-az.jpg",
    lang_id: 2,
  },
  {
    id: 4,
    name: "apa.az/az",
    link: "https://apa.az/az/rss",
    logo_suffix: "apa-az.jpg",
    lang_id: 0,
  },
  {
    id: 5,
    name: "metbuat.az",
    link: "https://metbuat.az/rss.xml",
    logo_suffix: "metbuat-az.jpg",
    lang_id: 0,
  },
  {
    id: 6,
    name: "azertag.az",
    link: "https://azertag.az/rss",
    logo_suffix: "azertag-az.jpg",
    lang_id: 0,
  },
  {
    id: 7,
    name: "lent.az",
    link: "https://lent.az/rss",
    logo_suffix: "lent-az.jpg",
    lang_id: 0,
  },
  {
    id: 8,
    name: "trend.az",
    link: "https://az.trend.az/feeds/index.rss",
    logo_suffix: "trend-az.jpg",
    lang_id: 0,
  },
  {
    id: 9,
    name: "day.az",
    link: "https://news.day.az/rss/",
    logo_suffix: "day-az.jpg",
    lang_id: 0,
  },
  {
    id: 10,
    name: "yenisabah.az",
    link: "https://yenisabah.az/rss/latest-posts",
    logo_suffix: "yenisabah-az.jpg",
    lang_id: 0,
  },
  {
    id: 11,
    name: "qafqazinfo.az",
    link: "https://qafqazinfo.az/rss",
    logo_suffix: "qafqazinfo-az.jpg",
    lang_id: 0,
  },
  {
    id: 12,
    name: "milli.az",
    link: "https://www.milli.az/feed.php",
    logo_suffix: "milli-az.jpg",
    lang_id: 0,
  },
  {
    id: 13,
    name: "musavat.com",
    link: "https://musavat.com/rss.xml",
    logo_suffix: "musavat-com.jpg",
    lang_id: 0,
  },
  {
    id: 14,
    name: "olke.az",
    link: "https://olke.az/feed",
    logo_suffix: "olke-az.jpg",
    lang_id: 0,
  },
  {
    id: 15,
    name: "sputnik.az",
    link: "https://sputnik.az/export/rss2/archive/index.xml",
    logo_suffix: "sputnik-az.jpg",
    lang_id: 0,
  },
  {
    id: 16,
    name: "haqqin.az",
    link: "https://haqqin.az/rss.xml",
    logo_suffix: "haqqin-az.jpg",
    lang_id: 0,
  },
  {
    id: 17,
    link: "https://meduza.io/rss2/all",
    name: "meduza.io",
    logo_suffix: "meduza-io.jpg",
    lang_id: 2,
  },
  {
    id: 18,
    link: "https://iz.ru/xml/rss/all.xml",
    name: "iz.ru",
    logo_suffix: "iz-ru.jpg",
    lang_id: 2,
  },
  {
    id: 19,
    name: "rbc.ru",
    link: "http://static.feed.rbc.ru/rbc/logical/footer/news.rss",
    logo_suffix: "rbc-ru.jpg",
    lang_id: 2,
  },
  {
    id: 20,
    name: "rt.com",
    link: "https://russian.rt.com/rss",
    logo_suffix: "rt-com.jpg",
    lang_id: 2,
  },
  {
    id: 21,
    name: "ria.ru",
    link: "https://ria.ru/export/rss2/archive/index.xml",
    logo_suffix: "ria-ru.jpg",
    lang_id: 2,
  },
  {
    id: 22,
    name: "lenta.ru",
    link: "https://lenta.ru/rss",
    logo_suffix: "lenta-ru.jpg",
    lang_id: 2,
  },
  {
    id: 23,
    name: "vesti.ru",
    link: "https://www.vesti.ru/vesti.rss",
    logo_suffix: "vesti-ru.jpg",
    lang_id: 2,
  },
  {
    id: 24,
    name: "oxu.az/ru",
    link: "https://ru.oxu.az/feed",

    logo_suffix: "oxu-az.jpg",
    lang_id: 2,
  },
  {
    id: 25,
    name: "hurriyet.com.tr",
    link: "http://www.hurriyet.com.tr/rss/anasayfa",
    logo_suffix: "hurriyet-com-tr.jpg",
    lang_id: 1,
  },
  {
    id: 26,
    name: "webrazzi.com",
    link: "https://webrazzi.com/feed",
    category_alias_name: "technology",
    logo_suffix: "webrazzi-com.jpg",
    lang_id: 1,
  },
  {
    id: 27,
    name: "transfermarkt.com.tr",
    link: "https://www.transfermarkt.com.tr/rss/news",
    category_alias_name: "sport",
    logo_suffix: "transfermarkt-com-tr.jpg",
    lang_id: 1,
  },
  {
    id: 28,
    name: "haberler.com",
    logo_suffix: "haberler-com.jpg",
    link: "https://rss.haberler.com/rss.asp",
    lang_id: 1,
  },
  {
    id: 29,
    name: "sabah.com.tr",
    logo_suffix: "sabah-com-tr.jpg",
    link: "https://www.sabah.com.tr/rss/anasayfa.xml",
    lang_id: 1,
  },
  {
    id: 30,
    name: "haberturk.com",
    logo_suffix: "haberturk-com.jpg",
    link: "https://www.haberturk.com/rss",
    lang_id: 1,
  },
  {
    id: 31,
    name: "fontanka.ru",
    logo_suffix: "fontanka-ru.jpg",
    link: "https://www.fontanka.ru/rss.xml",
    lang_id: 2,
  },
  {
    id: 32,
    name: "sports.ru",
    logo_suffix: "sports-ru.jpg",
    link: "https://www.sports.ru/rss/main.xml",
    category_alias_name: "sport",
    lang_id: 2,
  },
  {
    id: 33,
    name: "gazeta.ru",
    link: "https://www.gazeta.ru/export/rss/lenta.xml",
    logo_suffix: "gazeta-ru.jpg",
    lang_id: 2,
  },
  {
    id: 34,
    name: "cnnturk.com",
    link: "https://www.cnnturk.com/feed/rss/all/news",
    logo_suffix: "cnnturk-com.jpg",
    lang_id: 1,
  },
  {
    id: 35,
    name: "bbc.com/azeri",
    logo_suffix: "bbc-com.jpg",
    link: "https://feeds.bbci.co.uk/azeri/rss.xml",
    lang_id: 0,
  },
  {
    id: 36,
    name: "bbc.com/turkce",
    logo_suffix: "bbc-com.jpg",
    link: "https://feeds.bbci.co.uk/turkce/rss.xml",
    lang_id: 1,
  },
  {
    id: 37,
    name: "bbc.com/russian",
    logo_suffix: "bbc-com.jpg",
    link: "https://feeds.bbci.co.uk/russian/rss.xml",
    lang_id: 2,
  },
  {
    id: 38,
    name: "baku.ws/az",
    logo_suffix: "baku-ws.jpg",
    link: "https://baku.ws/rss.xml",
    lang_id: 0,
  },
  {
    id: 39,
    name: "baku.ws/ru",
    logo_suffix: "baku-ws.jpg",
    link: "https://ru.baku.ws/rss.xml",
    lang_id: 2,
  },
  {
    id: 40,
    name: "teleqraf.com",
    logo_suffix: "teleqraf-com.jpg",
    link: "https://teleqraf.com/feed.php",
    lang_id: 0,
  },
  {
    id: 41,
    name: "afn.az",
    logo_suffix: "afn-az.jpg",
    link: "https://afn.az/rss.xml",
    lang_id: 0,
  },
  {
    id: 42,
    name: "publika.az",
    logo_suffix: "publika-az.jpg",
    link: "https://publika.az/rss",
    lang_id: 0,
  },
  {
    id: 43,
    name: "yenicag.az",
    logo_suffix: "yenicag-az.jpg",
    link: "https://yenicag.az/feed",
    lang_id: 0,
  },
  {
    id: 44,
    name: "yenicag.info",
    logo_suffix: "yenicag-info.jpg",
    link: "https://yenicag.info/feed",
    lang_id: 1,
  },
  {
    id: 45,
    name: "novayaepoxa.com",
    logo_suffix: "novayaepoxa-com.jpg",
    link: "https://novayaepoxa.com/feed",
    lang_id: 2,
  },
  {
    id: 46,
    name: "vesti.az",
    logo_suffix: "vesti-az.jpg",
    link: "https://vesti.az/rss",
    lang_id: 0,
  },
  {
    id: 47,
    name: "The Guardian UK",
    logo_suffix: "theguardian-com.jpg",
    link: "https://theguardian.com/uk/rss",
    category_alias_name: "uk",
    lang_id: 3,
  },
  {
    id: 48,
    name: "The Guardian World",
    logo_suffix: "theguardian-com.jpg",
    link: "https://theguardian.com/world/rss",
    category_alias_name: "us",
    lang_id: 3,
  },
  {
    id: 49,
    name: "The Guardian Football",
    logo_suffix: "theguardian-com.jpg",
    link: "https://theguardian.com/football/rss",
    category_alias_name: "football",
    lang_id: 3,
  },
  {
    id: 50,
    name: "New York Times",
    logo_suffix: "nytimes-com.jpg",
    link: "https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml",
    lang_id: 3,
  },
  {
    id: 51,
    name: "CNN International Edition",
    logo_suffix: "cnn-com.jpg",
    link: "http://rss.cnn.com/rss/edition.rss",
    lang_id: 3,
  },
  {
    id: 52,
    name: "CNN Football Edition",
    logo_suffix: "cnn-com.jpg",
    link: "http://rss.cnn.com/rss/edition_football.rss",
    category_alias_name: "football",
    lang_id: 3,
  },
  {
    id: 53,
    name: "Caught Offside",
    logo_suffix: "caughtoffside-com.jpg",
    link: "https://www.caughtoffside.com/feed",
    category_alias_name: "football",
    lang_id: 3,
  },
  {
    id: 53,
    name: "TEAMTalk",
    logo_suffix: "teamtalk-com.jpg",
    link: "https://www.teamtalk.com/rss",
    category_alias_name: "football",
    lang_id: 3,
  },
  {
    id: 54,
    name: "Goal",
    logo_suffix: "goal-com.jpg",
    link: "https://goal.com/feeds/en/news",
    category_alias_name: "football",
    lang_id: 3,
  },
  {
    id: 55,
    name: "Goal Türkçe",
    logo_suffix: "goal-com.jpg",
    link: "https://goal.com/feeds/tr/news",
    category_alias_name: "football",
    lang_id: 1,
  },
  {
    id: 56,
    name: "BBC World",
    logo_suffix: "bbc-com.jpg",
    link: "https://feeds.bbci.co.uk/news/world/rss.xml",
    category_alias_name: "world",
    lang_id: 3,
  },
  {
    id: 57,
    name: "BBC Edition",
    logo_suffix: "bbc-com.jpg",
    link: "https://feeds.bbci.co.uk/news/rss.xml",
    lang_id: 3,
  },
];
