export const langs = [
  { id: 1, name: "az" },
  { id: 2, name: "tr" },
  { id: 3, name: "ru" },
  { id: 4, name: "en" },
];
export const sources = [
  {
    id: 1,
    name: "oxu.az",
    link: "https://oxu.az/feed",
    lang_id: 1,
  },
  {
    id: 2,
    name: "report.az",
    link: "https://report.az/rss",
    lang_id: 1,
  },
  {
    id: 3,
    name: "apa.az/ru",
    link: "https://apa.az/ru/rss",
    lang_id: 3,
  },
  {
    id: 4,
    name: "apa.az/az",
    link: "https://apa.az/az/rss",
    lang_id: 1,
  },
  {
    id: 5,
    name: "metbuat.az",
    link: "https://metbuat.az/rss.xml",
    lang_id: 1,
  },
  {
    id: 6,
    name: "azertag.az",
    link: "https://azertag.az/rss",
    lang_id: 1,
  },
  {
    id: 7,
    name: "lent.az",
    link: "https://lent.az/rss",
    lang_id: 1,
  },
  {
    id: 8,
    name: "trend.az",
    link: "https://az.trend.az/feeds/index.rss",
    lang_id: 1,
  },
  {
    id: 9,
    name: "day.az",
    link: "https://news.day.az/rss/",
    lang_id: 1,
  },
  {
    id: 10,
    name: "azadliq.az",
    link: "https://www.azadliq.az/feed",
    lang_id: 1,
  },
  {
    id: 11,
    name: "qafqazinfo.az",
    link: "https://qafqazinfo.az/rss",
    lang_id: 1,
  },
  {
    id: 12,
    name: "milli.az",
    link: "https://www.milli.az/feed.php",
    lang_id: 1,
  },
  {
    id: 13,
    name: "musavat.com",
    link: "https://musavat.com/rss.xml",
    lang_id: 1,
  },
  {
    id: 14,
    name: "olke.az",
    link: "https://olke.az/feed",
    lang_id: 1,
  },
  {
    id: 15,
    name: "sputnik.az",
    link: "https://sputnik.az/export/rss2/archive/index.xml",
    lang_id: 1,
  },
  {
    id: 16,
    name: "haqqin.az",
    link: "https://haqqin.az/rss.xml",
    lang_id: 1,
  },
  {
    id: 17,
    link: "https://meduza.io/rss2/all",
    name: "meduza.io",
    lang_id: 3,
  },
  {
    id: 18,
    link: "https://iz.ru/xml/rss/all.xml",
    name: "iz.ru",
    lang_id: 3,
  },
  {
    id: 19,
    name: "rbc.ru",
    link: "http://static.feed.rbc.ru/rbc/logical/footer/news.rss",
    lang_id: 3,
  },
  {
    id: 20,
    name: "rt.com",
    link: "https://russian.rt.com/rss",
    lang_id: 3,
  },
  {
    id: 21,
    name: "ria.ru",
    link: "https://ria.ru/export/rss2/archive/index.xml",
    lang_id: 3,
  },
  {
    id: 22,
    name: "lenta.ru",
    link: "https://lenta.ru/rss",
    lang_id: 3,
  },
  {
    id: 23,
    name: "vesti.ru",
    link: "https://www.vesti.ru/vesti.rss",
    lang_id: 3,
  },
  { id: 24, name: "ru.oxu.az", link: "https://ru.oxu.az/feed", lang_id: 3 },
  {
    id: 25,
    name: "hurriyet.com.tr",
    link: "http://www.hurriyet.com.tr/rss/anasayfa",
    lang_id: 2,
  },
  {
    id: 26,
    name: "webrazzi.com",
    link: "https://webrazzi.com/feed",
    lang_id: 2,
  },
];
